### ISSUE TITLE
when tensorflow implementation release

### ISSUE THREAD

**Issue by emma-sjwang** [WeitaoVan/L-GM-loss#1]
Hello!
Thanks for your wonderful work and sharing.
Just wonder when will release the tensorflow version of L-GM loss.

Thanks a lot.

**Comment by WeitaoVan** [comment]
Hi, Emma

For the tensorflow code, I have tested the classification task only on small datasets such as CIFAR100.

In fact the implementation in Tensorflow is straightforward. Because you don't have to write back-propagation. You can write the loss according to the formulation. For convenience and better convergence, you can first try fixing the covariance matrix to Identity Matrix. :)
I will release the tensorflow code very soon.

Best wishes.

**Comment by WeitaoVan** [comment]
Hi, 
it is released now.
